// Objective-C API for talking to twostack.org/zklib Go package.
//   gobind -lang=objc twostack.org/zklib
//
// File is generated by gobind. Do not edit.

#ifndef __Zklib_H__
#define __Zklib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * export
 */
FOUNDATION_EXPORT NSString* _Nonnull ZklibHello(NSString* _Nullable name);

#endif
